package day3.mite;

public class BlackBox extends LoadRunner
{

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		LoadRunner load=new BlackBox();
		load.testcases();
		load=new Selenium();
		load.testcases();
	}
	
	
	
	//@Override
	public void testcases()
	{
		System.out.println("Generated by user as well as automatic");
	}
}
class Selenium extends LoadRunner
{
	@Override
	public void testcases()
	{
		System.out.println("Selenium auto");
	}
}

abstract class LoadRunner
{
	public void test()
	{
		System.out.println("Load capacity of site");
	}
	abstract public void testcases(); 
}



